
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/proj-happycows-f23-5pm-4
owner: ucsb-cs156-f23
repo_name: proj-happycows-f23-5pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjY0Mjg2NjM1","is_bot":false,"login":"katytsao","name":"Katy Tsao"},"headRefName":"Katy-EndDates","number":27,"title":"Add Last Date field to Commons","url":"https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-4/pull/27"},{"author":{"id":"MDQ6VXNlcjU5MjUwODA=","is_bot":false,"login":"ajs808","name":"Arul Saxena"},"headRefName":"Arul-DefaultPropertiesFrontend","number":26,"title":"Arul default properties frontend","url":"https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-4/pull/26"},{"author":{"id":"MDQ6VXNlcjQ2Njk2NDkw","is_bot":false,"login":"mitali-g","name":"Mitali Gaidhani"},"headRefName":"Mitali-instr-report-improv","number":25,"title":"UI Improvements to Instructor Report Page","url":"https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-4/pull/25"},{"author":{"id":"MDQ6VXNlcjU0Mjg0MTQ4","is_bot":false,"login":"kendrick-lee","name":""},"headRefName":"Kendrick-UXLeaderboardPage","number":22,"title":"Added UX Features to Leadboard Page ","url":"https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-4/pull/22"}]
