
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/proj-happycows-f23-5pm-4
owner: ucsb-cs156-f23
repo_name: proj-happycows-f23-5pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjU5MjUwODA=","is_bot":false,"login":"ajs808","name":"Arul Saxena"},"headRefName":"Arul-ChatUX","number":30,"title":"Update chat message UX in play page","url":"https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-4/pull/30"},{"author":{"id":"MDQ6VXNlcjQ2Njk2NDkw","is_bot":false,"login":"mitali-g","name":"Mitali Gaidhani"},"headRefName":"Mitali-commonlist-default","number":29,"title":"Refactor CommonList Component To Have Default UI","url":"https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-4/pull/29"},{"author":{"id":"MDQ6VXNlcjU5MjUwODA=","is_bot":false,"login":"ajs808","name":"Arul Saxena"},"headRefName":"Arul-ChatButtonUX","number":28,"title":"Improve chat button UX in play page","url":"https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-4/pull/28"},{"author":{"id":"MDQ6VXNlcjY0Mjg2NjM1","is_bot":false,"login":"katytsao","name":"Katy Tsao"},"headRefName":"Katy-EndDates","number":27,"title":"Add Last Date field to Commons","url":"https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-4/pull/27"}]
