
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/proj-happycows-f23-5pm-4
owner: ucsb-cs156-f23
repo_name: proj-happycows-f23-5pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjU5MjUwODA=","is_bot":false,"login":"ajs808","name":"Arul Saxena"},"headRefName":"Arul-DefaultProperties","number":21,"title":"Backend for default properties in Commons Create page","url":"https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-4/pull/21"},{"author":{"id":"MDQ6VXNlcjI1NTMzNjIw","is_bot":false,"login":"Francisc0Leyva","name":"Francisco Justin Leyva"},"headRefName":"Justin-feature-remove-notifs","number":17,"title":"remove toast message and tests","url":"https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-4/pull/17"}]
