
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/proj-happycows-f23-5pm-4
owner: ucsb-cs156-f23
repo_name: proj-happycows-f23-5pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjU0Mjg0MTQ4","is_bot":false,"login":"kendrick-lee","name":""},"headRefName":"Kendrick-UXCommonsList","number":35,"title":"Fixed UI/UX Admin Commons List Page","url":"https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-4/pull/35"},{"author":{"id":"MDQ6VXNlcjU5MjUwODA=","is_bot":false,"login":"ajs808","name":"Arul Saxena"},"headRefName":"Arul-ChatUXExtended","number":33,"title":"Further UI/UX improvements for commons chat","url":"https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-4/pull/33"},{"author":{"id":"MDQ6VXNlcjQ2Njk2NDkw","is_bot":false,"login":"mitali-g","name":"Mitali Gaidhani"},"headRefName":"Mitali-profits-display","number":32,"title":"Mitali profits display","url":"https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-4/pull/32"},{"author":{"id":"MDQ6VXNlcjU5MjUwODA=","is_bot":false,"login":"ajs808","name":"Arul Saxena"},"headRefName":"Arul-ChatUX","number":30,"title":"Differentiate user's own messages in commons chat","url":"https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-4/pull/30"}]
