package edu.ucsb.cs156.happiercows.entities;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;

import org.hibernate.annotations.CreationTimestamp;
import java.time.LocalDateTime; 
import java.util.Date;


@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Entity(name = "announcements_table")
public class AnnouncementsTable {
    
    // Unique autogenerated Id
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    // Required id of the associated commons
    private long commonsId;

    // required datetime to start showing announcement (default to current datetime) 
    // optional datetime to stop showing the announcement 
    private LocalDateTime start;
    
    @CreationTimestamp
    @Temporal(TemporalType.TIMESTAMP)
    private Date end;

    //announcement 
    private String announcement;
}
